cleanup

diff --git a/shellrc b/shellrc
--- a/shellrc
+++ b/shellrc
@@ -46,7 +46,7 @@ todo() {
     if [ -e ~/doc/todo ]; then
         vim ~/doc/todo
     else
-        echo "error: todo not found"
+        echo >&2 "error: todo not found"
         return 1
     fi
 }
